version: '3.8'

services:
  app:
    image: jenkins-pipeline-demo:${DOCKER_TAG:-latest}
    container_name: jenkins-demo-prod
    ports:
      - "80:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - JAVA_OPTS=-Xmx1g -Xms512m
    networks:
      - demo-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  demo-network:
    driver: bridge