version: '3.8'

services:
  app:
    image: jenkins-pipeline-demo:${DOCKER_TAG:-latest}
    container_name: jenkins-demo-staging
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=staging
      - JAVA_OPTS=-Xmx512m -Xms256m
    networks:
      - demo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  demo-network:
    driver: bridge